---
apiVersion: v1
kind: Namespace
metadata:
  name: example-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-app
  namespace: example-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-app
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-app
  namespace: example-app
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - certificaterequests
  verbs:
  - create
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-app
  namespace: example-app
roleRef:
  kind: Role
  name: example-app
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: example-app
---
apiVersion: v1
kind: Service
metadata:
  name: example-app
  namespace: example-app
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: example-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-app-config
  namespace: example-app
data:
  config.yaml: |
    http:
      port: "3000"
    aws:
      bucketName: jetstack-workload-foo
      region: eu-west-1
    gcp:
      bucketName: jetstack-workload-foo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      serviceAccountName: example-app
      containers:
      - name: example-app
        image: jetstack/spiffe-connector-example:$VERSION-$ARCH
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /etc/config
          name: config
          readOnly: true
        - mountPath: /.aws
          name: aws
          readOnly: true
        - mountPath: /.config/gcloud
          name: gcloud
          readOnly: true
      - name: spiffe-connector-client
        image: jetstack/spiffe-connector-client:$VERSION-$ARCH
        args:
          - --server-address=spiffe-connector.spiffe-connector.svc.cluster.local:9090
          - --server-spiffe-id=spiffe://demo.jetstack.net/ns/spiffe-connector/sa/spiffe-connector
          - --tls-cert-file=/var/run/secrets/spiffe.io/tls.crt
          - --tls-key-file=/var/run/secrets/spiffe.io/tls.key
          - --trusted-ca-file=/var/run/secrets/spiffe.io/ca.crt
        volumeMounts:
        - mountPath: /.aws
          name: aws
          readOnly: false
        - mountPath: /.config/gcloud
          name: gcloud
          readOnly: false
        - mountPath: /var/run/secrets/spiffe.io
          name: spiffe
          readOnly: true

      volumes:
      - name: aws
        emptyDir: {}
      - name: gcloud
        emptyDir: {}
      - name: spiffe
        csi:
          driver: spiffe.csi.cert-manager.io
          readOnly: true
          volumeAttributes:
            spiffe.csi.cert-manager.io/fs-group: "65534"
      - name: config
        configMap:
          name: example-app-config
          items:
          - key: config.yaml
            path: config.yaml
