---
apiVersion: v1
kind: Namespace
metadata:
  name: example-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-server
  namespace: example-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-server
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-server
  namespace: example-server
rules:
  - apiGroups:
      - cert-manager.io
    resources:
      - certificaterequests
    verbs:
      - create
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-server
  namespace: example-server
roleRef:
  kind: Role
  name: example-server
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: example-server
---
apiVersion: v1
kind: Service
metadata:
  name: example-server
  namespace: example-server
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    app: example-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-server
  namespace: example-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-server
  template:
    metadata:
      labels:
        app: example-server
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      serviceAccountName: example-server
      containers:
        - name: spiffe-demo-server
          image: jetstack/spiffe-demo-server:$VERSION-$ARCH
          args:
            - --tls-cert-file=/var/run/secrets/spiffe.io/tls.crt
            - --tls-key-file=/var/run/secrets/spiffe.io/tls.key
            - --trusted-ca-file=/var/run/secrets/spiffe.io/ca.crt
          volumeMounts:
            - mountPath: /var/run/secrets/spiffe.io
              name: spiffe
              readOnly: true
      volumes:
        - name: spiffe
          csi:
            driver: spiffe.csi.cert-manager.io
            readOnly: true
            volumeAttributes:
              spiffe.csi.cert-manager.io/fs-group: "65534"
