---
apiVersion: v1
kind: Namespace
metadata:
  name: example-client
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-client
  namespace: example-client
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-client
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-client
  namespace: example-client
rules:
  - apiGroups:
      - cert-manager.io
    resources:
      - certificaterequests
    verbs:
      - create
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-client
  namespace: example-client
roleRef:
  kind: Role
  name: example-client
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: example-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-client
  namespace: example-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-client
  template:
    metadata:
      labels:
        app: example-client
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      serviceAccountName: example-client
      containers:
        - name: spiffe-demo-server
          image: jetstack/spiffe-demo-client:$VERSION-$ARCH
          args:
            - "--server-address=example-server.example-server.svc.cluster.local:9090"
            - "--server-spiffe-id=spiffe://demo.jetstack.net/ns/example-server/sa/example-server"
            - "--tls-cert-file=/var/run/secrets/spiffe.io/tls.crt"
            - "--tls-key-file=/var/run/secrets/spiffe.io/tls.key"
            - "--trusted-ca-file=/var/run/secrets/spiffe.io/ca.crt"
          volumeMounts:
            - mountPath: /var/run/secrets/spiffe.io
              name: spiffe
              readOnly: true
      volumes:
        - name: spiffe
          csi:
            driver: spiffe.csi.cert-manager.io
            readOnly: true
            volumeAttributes:
              spiffe.csi.cert-manager.io/fs-group: "65534"
