// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.4
// source: internal/pkg/server/proto/spiffedemo.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SpiffeDemoClient is the client API for SpiffeDemo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpiffeDemoClient interface {
	HelloWorld(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HelloWorldResponse, error)
}

type spiffeDemoClient struct {
	cc grpc.ClientConnInterface
}

func NewSpiffeDemoClient(cc grpc.ClientConnInterface) SpiffeDemoClient {
	return &spiffeDemoClient{cc}
}

func (c *spiffeDemoClient) HelloWorld(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HelloWorldResponse, error) {
	out := new(HelloWorldResponse)
	err := c.cc.Invoke(ctx, "/SpiffeDemo/HelloWorld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpiffeDemoServer is the server API for SpiffeDemo service.
// All implementations must embed UnimplementedSpiffeDemoServer
// for forward compatibility
type SpiffeDemoServer interface {
	HelloWorld(context.Context, *emptypb.Empty) (*HelloWorldResponse, error)
	mustEmbedUnimplementedSpiffeDemoServer()
}

// UnimplementedSpiffeDemoServer must be embedded to have forward compatible implementations.
type UnimplementedSpiffeDemoServer struct {
}

func (UnimplementedSpiffeDemoServer) HelloWorld(context.Context, *emptypb.Empty) (*HelloWorldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HelloWorld not implemented")
}
func (UnimplementedSpiffeDemoServer) mustEmbedUnimplementedSpiffeDemoServer() {}

// UnsafeSpiffeDemoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpiffeDemoServer will
// result in compilation errors.
type UnsafeSpiffeDemoServer interface {
	mustEmbedUnimplementedSpiffeDemoServer()
}

func RegisterSpiffeDemoServer(s grpc.ServiceRegistrar, srv SpiffeDemoServer) {
	s.RegisterService(&SpiffeDemo_ServiceDesc, srv)
}

func _SpiffeDemo_HelloWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpiffeDemoServer).HelloWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SpiffeDemo/HelloWorld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpiffeDemoServer).HelloWorld(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SpiffeDemo_ServiceDesc is the grpc.ServiceDesc for SpiffeDemo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpiffeDemo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SpiffeDemo",
	HandlerType: (*SpiffeDemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HelloWorld",
			Handler:    _SpiffeDemo_HelloWorld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/pkg/server/proto/spiffedemo.proto",
}
